### ISSUE TITLE
[feat-req] Allow navigating via command palette (keyboard navigation)

### ISSUE THREAD

**Issue by jd-solanki** [StarlaneStudios/vscode-comment-anchors#157] opened 2022-05-20 08:20 UTC
I really love how this extension grew since I started using it ❤️ 

Once more feature request came to mind recently was navigating via command palette instead of panel.

## Why?

Recently, I suggested this extension to one of my friends and he told me that is it possible to navigate between anchors using a command palette because he had lots of anchors in a single PHP file and find it in a long list of anchors wasn't efficient for him.

It will be a great productivity boost to allow searching and navigating through keyboard shortcuts (command palette)

> I suggested him using `SECTION` for long list but still keyboard navigation is better

Thanks for this awesome extension.

**Comment by macjuul** [comment] 2022-10-08 16:54
Thanks for the suggestion! While I don't currently have the resources to implement this right now, I'll leave this issue open in case anyone is willing to submit a PR for this functionality.

**Comment by macjuul** [comment] 2022-10-08 18:39
Actually, I decided to look into this myself and have implemented it 🙂

Closing the issue as it does appear to be a duplicate of #27 and has now been implemented.

**Closed by macjuul** 2022-10-08 18:39 UTC
Labels: Enhancement, Waiting for PR

**Comment by jd-solanki** [comment] 2022-10-10 07:03
Hi @macjuul 

Thanks for providing keyboard navigation ❤️ 

However,
1. It breaks the duplicating line in mac (_maybe only I have configured it or this is for all mac users_) - Duplicating the line via `shift + option + up/down` is not working anymore with the latest release of this extension.
2. This issue is regarding searching the comment anchor and navigating it.

For 2, Assume you have 15 anchors and anchor desc/name is the function name. I am at 1st anchor and the function I want to navigate to is at 13 and I know the anchor's name. With the current implementation, I need 10+ keystrokes to get there.

It will be time-saving if we introduce a command pellet to search and navigate to that anchor.

Thanks.

**Comment by macjuul** [comment] 2022-10-10 07:39
I can look into changing the default keybinds (you can manually change them for now). I was thinking of something along the lines of `Alt + C + Up/Down`, any thoughts on that?

As for your second point, I'll see if I can find an effective way to implement full command based navigation using the APIs exposed by vscode.

**Comment by macjuul** [comment] 2022-10-10 11:20
Quick navigation will be available in the next release.

![image](https://user-images.githubusercontent.com/7606171/194854596-860dbda3-4021-4f98-90cc-12bc2c2b658f.png)

**Comment by jd-solanki** [comment] 2022-10-10 11:32
Awesome ❤️ 

You are so quick at it 🏃🏻 

Thanks :)
