### ISSUE TITLE
Suggestion: color the comment before the tag

### ISSUE THREAD

**Issue by firas724** [StarlaneStudios/vscode-comment-anchors#132] opened 2021-10-29 00:52 UTC
Hello, thank you for the great extension. I think the visibility of the anchors would be much greater if the comment before the tag is also colored by the color of the tag. I write in python and sometimes I put several hashtags to highlight a note (make it stand out more) and if those are colored too it would be very helpful. (similar to the better comment extension)

**Comment by Maelep** [comment] 2022-01-08 09:20
I'm also interested by this feature but not by default, I would prefer a parameter like `"styleSlash": true`.

**Comment by macjuul** [comment] 2022-10-08 20:01
Duplicate of #31 which has just been implemented and will be available in the next release.

**Closed by macjuul** 2022-10-08 20:01 UTC
