### ISSUE TITLE
manual , how to use vscode comment anchors

### ISSUE THREAD

**Issue by boris2024** [StarlaneStudios/vscode-comment-anchors#159] opened 2022-05-31 03:34 UTC
hi there,
I hope this message finds you well.

I'm new to vs code and programming in general.

Is there a manual on how to use your extension? 
I have read the description and it sounds ideal for newbies and even for experienced programmer. Changing font color should be very very useful for programmers.

please let me know if this manual is available, 
thank you,

alvaro

**Comment by LucasFA** [comment] 2022-08-14 01:26
Duplicate of #158

**Comment by macjuul** [comment] 2022-10-08 14:20
Closing as duplicate of #158

**Closed by macjuul** 2022-10-08 14:20 UTC
