### ISSUE TITLE
Bug: custom tag shows double ahcnor icon in gutter

### ISSUE THREAD

**Issue by lonix1** [StarlaneStudios/vscode-comment-anchors#36] opened 2019-01-31 17:44 UTC
steps
- in config: ensure gutter icons are shown
- in config: add a custom tag, e.g. "TEST"
- in code: add a comment anchor, e.g. `//TEST test this new stuff`

results
- anchor is shown on a line (OK)
- same anchor also shown on the line below it (BUG)

Note that the bug occurs only when there is no space at the end of the comment, so:
- ok: `"//TEST test this new stuff "`          <--- note the trailing space
- bug: `"//TEST test this new stuff"`

**Comment by macjuul** [comment] 2019-02-03 01:37
Hi there!

I'm unable to reproduce this issue. Could you please include a screenshot/snippet of this bug in action?

Thanks!

**Comment by lonix1** [comment] 2019-02-03 04:44
![screenshot](https://user-images.githubusercontent.com/40320097/52172774-1cdbaf80-277f-11e9-8fd8-92792eeaabb1.png)

**Comment by ahmednrana** [comment] 2019-02-16 21:11
Hi Ionix1, Its not related to this issue but how did you add a custom tag. Which settings file did you edit for that? or can you paste the code for your custom tag. I tried but couldnt add one.

**Comment by lonix1** [comment] 2019-02-17 06:27
@ahmednrana The answer [is here](https://github.com/ExodiusStudios/vscode-comment-anchors#configuration). Just add the custom tags to your workspace settings. Open the json file (not the UI) and you'll see examples of how to add new tags.

Please open another issue for that if you get stuck.

**Comment by lonix1** [comment] 2019-02-17 06:29
@macjuul Did you manage to repro the issue? Maybe my idea that it has something to do with trailing spaces is incorrect, but the issue it still there. Not sure what it could be.

**Comment by JordanDi123** [comment] 2023-03-08 03:55
I made a custom tag to try and reproduce this issue and while it does appear to create a phantom anchor after going to a new line, this seems to only be the case for a very short period of time before it corrects itself.

![Code_wAEwpx0aGo](https://user-images.githubusercontent.com/24500399/223615311-b50af872-cb68-4890-9ba2-4e4d78ff77fe.gif)

Given that this issue has been unable to be reproduced, I will close this. If you or anyone else is able to reproduce it, feel free to re-open. 

Thank you for using Comment Anchors!

**Closed by JordanDi123** 2023-03-08 03:55 UTC
Labels: Bug, Waiting for response
